// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNiHed5FxNgk14eDvGO_xqZY035CTjz-0',
    appId: '1:1086114862973:web:67ec63901c553cf1a0de14',
    messagingSenderId: '1086114862973',
    projectId: 'cv-genius-ecf66',
    authDomain: 'cv-genius-ecf66.firebaseapp.com',
    storageBucket: 'cv-genius-ecf66.firebasestorage.app',
    measurementId: 'G-FM6SEZGCFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHfPC9h3YHmRugTD7568FOTORoCAtJAI',
    appId: '1:1086114862973:android:738315294e3e4747a0de14',
    messagingSenderId: '1086114862973',
    projectId: 'cv-genius-ecf66',
    storageBucket: 'cv-genius-ecf66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyd9GZhwxnaJk1Hyff3-aR024JjtzWKNE',
    appId: '1:1086114862973:ios:4137c0b2b770e7e8a0de14',
    messagingSenderId: '1086114862973',
    projectId: 'cv-genius-ecf66',
    storageBucket: 'cv-genius-ecf66.firebasestorage.app',
    iosBundleId: 'com.example.cvgenius.cvGenius',
  );
}
